INSERT INTO tbl_address (address) VALUES ('1600 Pennsylvania Avenue NW, Washington, D.C.');
INSERT INTO tbl_address (address) VALUES ('221B Baker Street, London');
INSERT INTO tbl_address (address) VALUES ('Shibuya Crossing, Shibuya, Tokyo');
INSERT INTO tbl_address (address) VALUES ('1 Times Square, New York City');
INSERT INTO tbl_address (address) VALUES ('The Eiffel Tower, Champ de Mars, Paris');
INSERT INTO tbl_address (address) VALUES ('Red Square, Moscow');
INSERT INTO tbl_address (address) VALUES ('The Burj Khalifa, Downtown Dubai');
INSERT INTO tbl_address (address) VALUES ('The Great Wall of China, Huairou District, Beijing');
INSERT INTO tbl_address (address) VALUES ('The Sydney Opera House, Bennelong Point, Sydney');
INSERT INTO tbl_address (address) VALUES ('The Colosseum, Piazza del Colosseo, Rome');

INSERT INTO tbl_contact (first_Name, second_Name, birth_Date, personal_Photo) VALUES ('John', 'Doe', '1980-05-15', 'VGhpcyBpcyBhIHRlc3Qgc3RyaW5nIGluIGJhc2U2NCBzdHJpbmc=');
INSERT INTO tbl_contact (first_Name, second_Name, birth_Date, personal_Photo) VALUES ('Jane', 'Doe', '1985-03-22', 'VGhpcyBpcyBhIHRlc3Qgc3RyaW5nIGluIGJhc2U2NCBzdHJpbmc=');
INSERT INTO tbl_contact (first_Name, second_Name, birth_Date, personal_Photo) VALUES ('Michael', 'Smith', '1976-12-01', 'VGhpcyBpcyBhIHRlc3Qgc3RyaW5nIGluIGJhc2U2NCBzdHJpbmc=');
INSERT INTO tbl_contact (first_Name, second_Name, birth_Date, personal_Photo) VALUES ('Emily', 'Johnson', '1992-08-07', 'VGhpcyBpcyBhIHRlc3Qgc3RyaW5nIGluIGJhc2U2NCBzdHJpbmc=');
INSERT INTO tbl_contact (first_Name, second_Name, birth_Date, personal_Photo) VALUES ('William', 'Brown', '1988-02-14', 'VGhpcyBpcyBhIHRlc3Qgc3RyaW5nIGluIGJhc2U2NCBzdHJpbmc=');
INSERT INTO tbl_contact (first_Name, second_Name, birth_Date, personal_Photo) VALUES ('Olivia', 'Davis', '1997-11-03', 'VGhpcyBpcyBhIHRlc3Qgc3RyaW5nIGluIGJhc2U2NCBzdHJpbmc=');
INSERT INTO tbl_contact (first_Name, second_Name, birth_Date, personal_Photo) VALUES ('David', 'Miller', '1982-06-19', 'VGhpcyBpcyBhIHRlc3Qgc3RyaW5nIGluIGJhc2U2NCBzdHJpbmc=');
INSERT INTO tbl_contact (first_Name, second_Name, birth_Date, personal_Photo) VALUES ('Sophia', 'Wilson', '1990-04-25', 'VGhpcyBpcyBhIHRlc3Qgc3RyaW5nIGluIGJhc2U2NCBzdHJpbmc=');
INSERT INTO tbl_contact (first_Name, second_Name, birth_Date, personal_Photo) VALUES ('Christopher', 'Taylor', '1987-09-12', 'VGhpcyBpcyBhIHRlc3Qgc3RyaW5nIGluIGJhc2U2NCBzdHJpbmc=');
INSERT INTO tbl_contact (first_Name, second_Name, birth_Date, personal_Photo) VALUES ('Isabella', 'Anderson', '1995-01-30', 'VGhpcyBpcyBhIHRlc3Qgc3RyaW5nIGluIGJhc2U2NCBzdHJpbmc=');

INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+1-202-555-0160', 1);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+44-207-555-0100', 2);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+81-3-5555-0199', 3);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+86-10-5555-0100', 4);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+33-1-5555-0100', 5);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+7-495-555-0100', 6);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+971-4-555-0100', 7);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+86-21-5555-0100', 8);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+61-2-5555-0100', 9);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+39-06-5555-0100', 10);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+52-55-5555-0100', 1);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+81-6-5555-0100', 2);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+7-812-555-0100', 3);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+34-91-555-0100', 4);
INSERT INTO tbl_phone_Number (phone_Number, contact_Id) VALUES ('+86-755-5555-0100', 5);

INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (1, 9);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (2, 6);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (3, 4);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (4, 1);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (5, 7);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (6, 5);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (7, 10);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (8, 2);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (9, 3);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (10, 8);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (1, 8);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (2, 9);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (3, 6);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (4, 2);
INSERT INTO tbl_contact_address (contact_Id, address_Id) VALUES (5, 5);